site_name: kophy's notes
repo_url: https://github.com/kophy/Notes

theme:
  name: "sandstone"

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - mdx_truly_sane_lists

pages:
    - Home: 'index.md'
    - Infrastructure:
      - Storage:
        - aurora: 'aurora/aurora.md'
        - bigtable: 'bigtable/bigtable.md'
        - dynamo: 'dynamo/dynamo.md'
        - espresso: 'espresso/espresso.md'
        - f1: 'f1/f1.md'
        - gfs: 'gfs/gfs.md'
        - gorilla: 'gorilla/gorilla.md'
        - spanner: 'spanner/spanner.md'
        - tao: 'tao/tao.md'
      - Data Processing:
        - mapreduce: 'mapreduce/mapreduce.md'
        - flink: 'flink/flink.md'
        - flume: 'flume/flume.md'
        - rdd: 'rdd/rdd.md'
        - d-stream: 'd-stream/d-stream.md'
        - millwheel: 'millwheel/millwheel.md'
        - pregel: 'pregel/pregel.md'
        - storm: 'storm/storm.md'
      - Cluster Management:
        - borg: 'borg/borg.md'
        - zookeeper: 'zookeeper/zookeeper.md'
      - Misc:
        - databus: 'databus/databus.md'
        - kafka: 'kafka/kafka.md'
        - zfs: 'zfs/zfs.md'
    - Machine Learning:
      - Embedding:
        - word2vec: 'word2vec/word2vec.md'
    - Advertisement:
      - CTR:
        - predicting-clicks: 'predicting-clicks/predicting-clicks.md'
